# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
vector = np.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
vector2 = np.arange(10, 49)
vector2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [4]:
vector2.shape

(39,)

5. Print the type of the previous array in question 3

In [5]:
vector2.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:
print(np.__version__, np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
1.18.4 None


7. Print the dimension of the array in question 3


In [7]:
vector2.ndim

1

8. Create a boolean array with all the True values

In [8]:
vector3 = np.array(range(1, 10), dtype="bool")
vector3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

9. Create a two dimensional array




In [13]:
array1 = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
array2 = np.zeros((3,3))
array2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

10. Create a three dimensional array



In [22]:
a_3d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a_3d_array)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
array3 = np.zeros((3,3,3))
array3

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [25]:
original=np.array(range(90, 100))
print("Original: ", original)
print("reversed:  ", original[::-1])

Original:  [90 91 92 93 94 95 96 97 98 99]
reversed:   [99 98 97 96 95 94 93 92 91 90]


In [26]:
reverse_vector = np.array(range(1, 10))
print("Original: ", reverse_vector)

reverse_vector[0], reverse_vector[len(reverse_vector) - 1] = reverse_vector[len(reverse_vector) - 1], reverse_vector[0]

print("Reversed: ", reverse_vector)


Original:  [1 2 3 4 5 6 7 8 9]
Reversed:  [9 2 3 4 5 6 7 8 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [28]:
null_vector  = np.zeros(10)
null_vector[5] = 1

null_vector



array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [30]:
identitiy_matrix = np.identity(3)

identitiy_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [34]:
array0  = np.array([1, 2, 3, 4, 5])
print('initially datatype = ',array0.dtype)
array0 = array0.astype(np.float32)
print('converted datatype = ',array0.dtype)

initially datatype =  int32
converted datatype =  float32


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [35]:
arr1 = np.array([[1., 2., 3.] ,[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.] ,[7., 2., 12.]])

np.multiply(arr1, arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [39]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

comparison = arr1 == arr2 
equal_arrays = comparison.all()  
print(equal_arrays) 

print("a > b") 
print(np.greater(arr1, arr2)) 

print("a >= b") 
print(np.greater_equal(arr1, arr2)) 

print("a < b") 
print(np.less(arr1, arr2)) 

print("a <= b") 
print(np.less_equal(arr1, arr2)) 

False
a > b
[[ True False  True]
 [False  True False]]
a >= b
[[ True False  True]
 [False  True False]]
a < b
[[False  True False]
 [ True False  True]]
a <= b
[[False  True False]
 [ True False  True]]


17. Extract all odd numbers from arr with values(0-9)

In [40]:
arr = np.arange(9)
filtered_array = filter(lambda val: val % 2 == 1, arr)
list(filtered_array)


[1, 3, 5, 7]

18. Replace all odd numbers to -1 from previous array

In [41]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [42]:
arr = np.arange(10)
arr[5] = arr[6] = arr[7] = arr[8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [48]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [49]:
arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

arr2d[1, 1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [50]:
arr3d = np.array([ [ [1, 2, 3], [4, 5, 6] ], [ [7, 8, 9], [10, 11, 12] ] ])

arr3d[0][:] =64

arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [53]:
arr = np.arange(9).reshape(3, 3)
arr2 = arr[0] #TODO
arr2

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [54]:
arr = np.arange(9).reshape(3, 3)
val = arr[1][1] #TODO
val

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [56]:
arr = np.arange(9).reshape(3, 3)
print(arr)
arr3 = arr[0:-1, -1]

arr3


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [63]:

arr=np.random.random((10,10))
print(arr.max(), arr.min())

print("max, min in columns")
maxInColumns = np.amax(arr, axis=1)
val1 = max(maxInColumns)
print("max value = ",val1)
val2 = min(maxInColumns)
print("max value = ",val2)

print("max, min in rows")
maxInColumns = np.amax(arr, axis=0)
val1 = max(maxInColumns)
print("max value = ",val1)
val2 = min(maxInColumns)
print("max value = ",val2)

0.9757071795602731 0.006715849037092436
max, min in columns
max value =  0.9757071795602731
max value =  0.6885143496559404
max, min in rows
max value =  0.9757071795602731
max value =  0.6390592701399181


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [64]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 

b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [65]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [66]:
import random

name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
# data = np.random.randn(7,4) # --> This gives floating point numbers
data = np.random.randint(7, size=random.randrange(1, 10))
print(data)
print(np.where(name[data] != "Will"))

[1 5 4 3 5 3 0]
(array([0, 1, 3, 4, 5, 6], dtype=int64),)


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [67]:
import random

name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
# data = np.random.randn(7,4) # --> This gives floating point numbers
data = np.random.randint(7, size=random.randrange(1, 10))
print(data)
print(np.where((name[data] != "Joe") & (name[data] != "Will")))

[6 5 0 2 1 2 4]
(array([2], dtype=int64),)


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [68]:
arr = np.random.uniform(low=1.0, high=15.0, size=(5,3))
arr

array([[ 5.2306931 ,  3.77819547,  8.45476699],
       [ 8.10059908,  1.24395993, 12.58518449],
       [ 5.33749359,  6.59116427, 12.96406824],
       [ 8.98887955,  6.53115696,  6.13825325],
       [13.53918104,  4.40479997,  5.454707  ]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [72]:
arr = np.random.uniform(low=1.0, high=16.0, size=(2,2,4))
arr

array([[[ 6.10931682, 10.8911171 ,  2.4691969 , 12.16405205],
        [12.04754458,  7.21435227,  6.25532584, 14.24557307]],

       [[ 9.76295454, 10.50966716, 11.08320366, 15.79487635],
        [ 3.19527692,  5.51109678,  4.60267945, 15.44492039]]])

33. Swap axes of the array you created in Question 32

In [73]:
np.swapaxes(arr, 0, 1)
arr

array([[[ 6.10931682, 10.8911171 ,  2.4691969 , 12.16405205],
        [12.04754458,  7.21435227,  6.25532584, 14.24557307]],

       [[ 9.76295454, 10.50966716, 11.08320366, 15.79487635],
        [ 3.19527692,  5.51109678,  4.60267945, 15.44492039]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [74]:
import math

arr = np.arange(10)
print(arr)
new_arr = filter(lambda x: x if math.sqrt(x) > 0.5 else 0, arr)
np.asarray(list(new_arr))


[0 1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [75]:
arr1 = np.random.randint(12, size=random.randrange(0, 12))
arr2 = np.random.randint(12, size=random.randrange(0, 12))
print(arr1)
print(arr2)
np.where(arr1 == arr2)

[9]
[7 8]


(array([], dtype=int64),)

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [76]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names) # --> returns sorted unique values

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [77]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
val = np.intersect1d(a, b)

a = filter(lambda x: x if x not in val else None, a)
np.asarray(list(a))

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [78]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
sampleArray[:, 1] = 10
sampleArray


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [79]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [80]:
matrix = np.random.randint(20, size=(random.randint(0, 5), random.randint(0, 5)))
np.cumsum(matrix)

array([12, 22, 37, 39, 57, 69], dtype=int32)